// ielts_data.js
// 100 Common IELTS General Training Writing Task 1 Expressions

const defaultSentences = [
    // --- Openings ---
    { text: "I am writing with regard to your advertisement", context: "Formal opening: Responding to a job or product ad." },
    { text: "I am writing to express my dissatisfaction with the service", context: "Formal opening: Starting a letter of complaint." },
    { text: "I am writing to request your assistance with a matter", context: "Formal opening: Asking for help professionally." },
    { text: "I am writing to inquire about the course details", context: "Formal opening: Asking for information." },
    { text: "I am writing to bring to your attention a serious issue", context: "Formal opening: Reporting a problem to authority." },
    { text: "I am writing to apologize for the inconvenience caused", context: "Formal opening: Making an apology." },
    { text: "I was wondering if you could do me a favor", context: "Semi-formal: Asking a friend or colleague for help." },
    { text: "I hope this letter finds you well", context: "Standard polite opening for friends or colleagues." },
    { text: "It has been a long time since we last met", context: "Informal opening: Reconnecting with a friend." },
    { text: "I am writing to express my interest in the position", context: "Formal: Applying for a job." },

    // --- Requests ---
    { text: "I would be grateful if you could provide more details", context: "Formal: Asking for information politely." },
    { text: "I would appreciate it if you could look into this", context: "Formal: Asking someone to investigate a problem." },
    { text: "Could you please let me know if you are available", context: "Formal/Semi-formal: Checking availability." },
    { text: "Please let me know if you require any further information", context: "Formal: Offering more help." },
    { text: "I would like to request a refund for the item", context: "Formal: Asking for money back." },
    { text: "Could you possibly help me with this project", context: "Semi-formal: Asking a colleague for help." },
    { text: "I would be obliged if you could send it urgently", context: "Very formal: Asking for speed." },
    { text: "Please confirm if this arrangement is suitable for you", context: "Formal: Checking if a plan works." },
    { text: "Kindly inform me of your decision at your earliest convenience", context: "Formal: Asking for a quick decision." },
    { text: "I would like to suggest a meeting next week", context: "Formal: Proposing a time to meet." },

    // --- Complaints ---
    { text: "I am extremely disappointed with the quality of the product", context: "Formal complaint: Expressing strong unhappiness." },
    { text: "The service I received was far below the expected standard", context: "Formal complaint: Bad service." },
    { text: "To make matters worse the staff were rude", context: "Formal complaint: Adding more bad news." },
    { text: "I expect a full refund or a replacement immediately", context: "Formal complaint: Demanding a solution." },
    { text: "I have yet to receive a response to my previous email", context: "Formal complaint: Chasing up a reply." },
    { text: "This situation has caused me a great deal of stress", context: "Formal complaint: Explaining impact." },
    { text: "It is my opinion that this issue requires urgent attention", context: "Formal: Emphasizing urgency." },
    { text: "I would like to make a formal complaint regarding your staff", context: "Formal: Officially complaining about people." },
    { text: "The item was damaged upon arrival", context: "Formal: Reporting broken goods." },
    { text: "Despite my previous requests the issue remains unresolved", context: "Formal: Complaining about a lingering problem." },

    // --- Apologies ---
    { text: "Please accept my sincere apologies for the inconvenience", context: "Formal apology: Standard professional apology." },
    { text: "I am terribly sorry for not attending the party", context: "Informal apology: Missing a social event." },
    { text: "I apologize for any confusion this may have caused", context: "Formal apology: Clarifying a misunderstanding." },
    { text: "Please forgive me for the delay in replying", context: "Semi-formal: Replying late." },
    { text: "I deeply regret the error made on our part", context: "Formal apology: Business mistake." },
    { text: "I assure you that this will not happen again", context: "Formal apology: Promising improvement." },
    { text: "I take full responsibility for the mistake", context: "Formal apology: Owning the error." },
    { text: "I am writing to let you know that I cannot come", context: "Semi-formal: Canceling plans." },
    { text: "Unfortunately I will not be able to attend the meeting", context: "Formal: Declining an invitation." },
    { text: "Please accept my apologies for the late submission", context: "Formal: Handing in work late." },

    // --- Gratitude ---
    { text: "Thank you for your prompt attention to this matter", context: "Formal closing: Urging action politely." },
    { text: "I am very grateful for your support", context: "Formal/Semi-formal: Saying thanks." },
    { text: "Thank you in advance for your cooperation", context: "Formal: Expecting help." },
    { text: "I really appreciate your help with this", context: "Semi-formal: Thanking a colleague." },
    { text: "Thank you for taking the time to read my letter", context: "Formal closing: Polite sign-off." },
    { text: "I cannot thank you enough for your kindness", context: "Personal: Deep gratitude." },
    { text: "Your assistance in this matter is greatly appreciated", context: "Formal: Thanking for help." },
    { text: "Thanks for inviting me to your wedding", context: "Informal: Acknowledging an invite." },
    { text: "I am writing to thank you for the wonderful gift", context: "Personal: Thank you note." },
    { text: "Thank you for your understanding regarding this issue", context: "Formal: Thanking for patience." },

    // --- Closings ---
    { text: "I look forward to hearing from you soon", context: "Standard formal closing." },
    { text: "Please do not hesitate to contact me", context: "Formal closing: Offering more contact." },
    { text: "I await your prompt response", context: "Formal closing: Expecting a quick reply." },
    { text: "Hoping for a favorable response", context: "Formal closing: Requesting/Job seeking." },
    { text: "Let's catch up properly soon", context: "Informal closing: Friends." },
    { text: "Give my regards to your family", context: "Semi-formal/Informal: Social closing." },
    { text: "I look forward to meeting you in person", context: "Formal closing: Before an interview." },
    { text: "Once again I apologize for the inconvenience", context: "Formal closing: Re-apologizing." },
    { text: "Please keep me informed of any developments", context: "Formal closing: Asking for updates." },
    { text: "Yours faithfully", context: "Formal sign-off: When you don't know the name." },
    { text: "Yours sincerely", context: "Formal sign-off: When you know the name." },

    // --- General Business & Social ---
    { text: "I am writing to confirm our appointment", context: "Formal: Confirming a date." },
    { text: "Could we reschedule our meeting to a later date", context: "Formal/Semi-formal: Changing plans." },
    { text: "I am afraid I have some bad news", context: "Semi-formal: Breaking bad news." },
    { text: "I would be delighted to accept your invitation", context: "Formal: Accepting an invite." },
    { text: "It was great to hear from you", context: "Informal: Replying to a friend." },
    { text: "I am writing to give you an update", context: "Formal: Providing new info." },
    { text: "Please find attached the documents you requested", context: "Formal email: Sending files." },
    { text: "I am concerned about the lack of communication", context: "Formal: Expressing worry." },
    { text: "We would like to invite you to our annual dinner", context: "Formal: Inviting someone." },
    { text: "I strongly recommend that you reconsider your decision", context: "Formal: Persuading/Suggesting." },

    // --- Additional Practice Mix ---
    { text: "I would like to apply for the vacancy", context: "Formal: Job application." },
    { text: "My current lease is due to expire soon", context: "Formal: Housing/Rent." },
    { text: "I am writing to terminate my contract", context: "Formal: Ending a service." },
    { text: "The noise from your apartment is unbearable", context: "Formal complaint: Neighbor issue." },
    { text: "I have lost my credit card", context: "Formal: Reporting loss." },
    { text: "Could you recommend a good hotel in the area", context: "Semi-formal: Asking advice." },
    { text: "I plan to visit your country next month", context: "Informal: Travel plans." },
    { text: "I am writing to resign from my position", context: "Formal: Quitting a job." },
    { text: "The food was cold and the service was slow", context: "Formal complaint: Restaurant." },
    { text: "I am writing to inquire about membership fees", context: "Formal: Asking about costs." },
    { text: "Please transfer the funds to my account", context: "Formal: Banking." },
    { text: "I have enclosed my CV for your review", context: "Formal: Job application." },
    { text: "I am eager to improve my English skills", context: "General statement." },
    { text: "Could you look after my pet while I am away", context: "Informal: Asking a favor." },
    { text: "I am unhappy with the local transport service", context: "Formal complaint: Public services." },
    { text: "I would like to volunteer for the charity event", context: "Formal: Offering help." },
    { text: "Please let me know if the time suits you", context: "Semi-formal: Scheduling." },
    { text: "I am writing to dispute the charge on my bill", context: "Formal: Money dispute." },
    { text: "I would love to come and stay with you", context: "Informal: Visiting friends." },
    { text: "I am concerned about the safety of the equipment", context: "Formal: Safety report." },
    { text: "Please acknowledge receipt of this letter", context: "Formal: Asking for confirmation." },
    { text: "I am writing to complain about the garbage collection", context: "Formal complaint: Council services." },
    { text: "I would be honored to speak at the conference", context: "Formal: Accepting a role." },
    { text: "I regret to inform you that your application failed", context: "Formal: Rejection." },
    { text: "Please send the package to the following address", context: "Formal: Shipping instruction." },
    { text: "I am writing to ask for some advice regarding a trip", context: "Semi-formal: Asking advice." },
    { text: "I felt it was important to inform you immediately", context: "Formal: Urgent news." },
    { text: "I would like to congratulate you on your success", context: "Formal/Semi-formal: Congratulations." },
    { text: "I am writing to suggest an improvement to the system", context: "Formal: Suggestion." },
    { text: "Please ensure that the work is completed by Friday", context: "Formal: Setting a deadline." },
    { text: "I am willing to pay for the repair costs", context: "Formal: Offering payment." },
    { text: "I am shocked by the increase in prices", context: "Formal complaint: Costs." },
    { text: "I would like to invite you to give a presentation", context: "Formal: Invitation." },
    { text: "I am writing to cancel my subscription", context: "Formal: Cancellation." },
    { text: "I look forward to a successful working relationship", context: "Formal closing: New business." },
    { text: "Thank you for your hospitality during my stay", context: "Formal/Semi-formal: Thank you." },
    { text: "I am writing to report a lost item", context: "Formal: Lost property." },
    { text: "I would appreciate your advice on this matter", context: "Formal: Seeking counsel." },
    { text: "Please accept this gift as a token of my appreciation", context: "Formal/Personal: Giving a gift." }
];